sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull jumperio/vlab-gcc-arm:latest

script:
- docker run -it --rm -v $PWD:/my_files_in_docker jumperio/vlab-gcc-arm
- cd my_files_in_docker
- make