version: 2
jobs:
  build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: build
          command: make
      - run:
          name: save result
          command: cp -f build/. $CIRCLE_ARTIFACTS/
