version: 2
jobs:
  build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: build
          command: echo $PWD && make
      - store_artifacts:
          path: build/*.bin
